### ISSUE TITLE
Git Push Error - gandalf not found

### ISSUE THREAD

**Issue by aaronfranco** [tsuru/gandalf#189]
Hello,

I have added SSH keys using tsuru key-add and I verified that all the files are created. Also, the mongodb database shows my user and keys were added properly. However, when I do a git push, I get the following error:

````
sh: 1: /usr/local/bin/gandalf: not found
fatal: Could not read from remote repository. 

Please make sure you have the correct access rights and the repository exists.
````

I know the repository exists, and the key is set up properly, or so it seems. Any advice on how I can fix this or perhaps on what I'm missing? 

Thanks for creating this and Tsuru, very useful and cool :+1:

**Comment by fsouza** [comment]
Hi @aaronfranco, how did you install Gandalf? Can you share your Gandalf configuration file? It's probably at ``/etc/gandalf.conf``.

**Comment by aaronfranco** [comment]
Hi @fsouza, thanks for the speedy reply! I installed with aptitude 

````sudo apt-get install gandalf-server```` 

Here is my config: 
````
bin-path: /usr/local/bin/gandalf
database:
  url: 127.0.0.1:27017
  name: gandalf
git:
  bare:
    location: /var/lib/gandalf/repositories
    template: /home/git/bare-template
host: localhost
bind: "0.0.0.0:8000"
uid: git
api:
  request:
    maxMemory: 2097152
repository:
  tempDir: /tmp
````
